---

- name: Set environment variables for httpd24
  template:
    src: sysconfig-httpd.j2
    dest: /opt/rh/httpd24/root/etc/sysconfig/httpd

- name: Enable SCL HTTPD 2.4 for interactive users
  copy:
    src: httpd24.sh
    dest: /etc/profile.d/httpd24.sh
    mode: 0755
    owner: root
    group: wheel

- name: Unset default DocumentRoot
  replace:
    dest: /opt/rh/httpd24/root/etc/httpd/conf/httpd.conf
    regexp: >
      ^DocumentRoot "\/opt\/rh\/httpd24\/root\/var\/www\/html"$
    replace: >
      # DocumentRoot "/opt/rh/httpd24/root/var/www/html"

- name: Copy 00-mpm.conf
  copy:
    src: 00-mpm.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/00-mpm.conf
    mode: 0644
    owner: root
    group: root

- name: Copy 00http2.conf
  copy:
    src: 00http2.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/00http2.conf
    mode: 0644
    owner: root
    group: root

- name: Copy 00gzip.conf
  copy:
    src: 00gzip.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/00gzip.conf
    mode: 0644
    owner: root
    group: root

- name: Copy 00cache.conf
  copy:
    src: 00gzip.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/00cache.conf
    mode: 0644
    owner: root
    group: root

- name: Copy ssl.conf
  copy:
    src: ssl.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/ssl.conf
    mode: 0644
    owner: root
    group: root

- name: 00ssl.include
  copy:
    src: 00ssl.include
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/00ssl.include
    mode: 0644
    owner: root
    group: root

- name: 00srv_default.conf
  copy:
    src: 00srv_default.conf
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/00srv_default.conf
    mode: 0644
    owner: root
    group: root

- name: Comment out the welcome conf
  command: sed -i "s/^[^#]/#&/" /opt/rh/httpd24/root/etc/httpd/conf.d/welcome.conf

- name: Set permissions for /srv
  file:
    path: /srv
    owner: apache
    group: apache
    mode: 0775

- name: Ensure /var/cache/httpd24 exists
  file:
    path: /var/cache/httpd24
    state: directory
    mode: 0755
    owner: apache
    group: apache
    recurse: yes
