---

- include: yum.yml
  become: true

- name: check if privkey exists
  stat:
    path: "{{ httpd_key_path }}/star.{{ httpd_dn_suffix }}/privkey.pem"
    follow: yes
  register: http_privkey_check

- name: check if cert exists
  stat: 
    path: "{{ httpd_cert_path }}/star.{{ httpd_dn_suffix }}/cert.pem"
    follow: yes
  register: http_cert_check

- name: check if chain exists
  stat: 
    path: "{{ httpd_cert_path }}/star.{{ httpd_dn_suffix }}/chain.pem"
    follow: yes
  register: http_chain_check

- include: ssl-selfsign.yml
  become: true
  when: http_privkey_check.stat.exists is not defined or http_cert_check.stat.exists is not defined or http_chain_check.stat.exists is not defined

- include: configure.yml
  become: true
