---

- name: Git letsencrypt.
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: "{{ letsencrypt_path }}"/build
    force: yes

- name: Ensure httpd24 is stopped
  service:
    name: httpd24-httpd
    state: stopped

- name: Generate key and CSR, and get a signed cert.
  command: >
     openssl req -newkey rsa:2048 -nodes -sha256 -x509 -subj "/O=Fake {{ httpd_fake_orgs | shuffle | first }} Organization No. {{ 1000 | random }}/OU=Fake {{ httpd_fake_units | shuffle |first }} Unit No. {{ 1000 | random }}/CN=*.{{ httpd_dn_suffix }}" -days 90 -keyout "{{ httpd_key_path }}"/star."{{ httpd_dn_suffix }}"/privkey.pem -out "{{ httpd_cert_path }}"/star."{{ httpd_dn_suffix }}"/cert.pem
  args:
    chdir: "{{ letsencrypt_path }}"/build
  with_items: sites

- name: Ensure httpd24 is started
  service:
    name: httpd24-httpd
    state: started
