---

- name: Ensure ssl cert directory exists
  file:
    path: "{{ httpd_cert_path }}/star.{{ httpd_dn_suffix }}"
    state: directory

- name: Ensure ssl key directory exists
  file:
    path: "{{ httpd_key_path }}/star.{{ httpd_dn_suffix }}"
    state: directory

- name: Ensure httpd24 is stopped
  service:
    name: httpd24-httpd
    state: stopped

- name: Generate a self-signed cert.
  become: true
  command: >
     openssl req -newkey rsa:2048 -nodes -sha256 -x509 -subj "/O=Fake {{ ['Technology','Government','Manufacturing'] | shuffle }} Organization No. {{ 1000 | random }}/OU=Fake {{ ['Human Resources','Public Relations','Accounting'] | shuffle }} Unit No. {{ 1000 | random }}//CN=*.{{ httpd_dn_suffix }}" -days 90 -keyout "{{ httpd_key_path }}"/star."{{ httpd_dn_suffix }}"/privkey.pem -out "{{ httpd_cert_path }}"/star."{{ httpd_dn_suffix }}"/cert.pem 

- name: Create a dummy chain file
  become: true
  shell: >
    echo \# > "{{ httpd_cert_path }}/star.{{ httpd_dn_suffix }}/chain.pem"

- name: Ensure httpd24 is started
  service:
    name: httpd24-httpd
    state: started
